title: Data, world!
description: > # this means to ignore newlines until "baseurl:"
  Everything is data
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jake Jeong # add your name
author-img: jake-jeong.jpg # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning.
social-twitter: jidasung
social-facebook: jidasung
social-github: jidasung
social-linkedin: jidasung
social-email: hunguenglish@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
